### ISSUE TITLE
A question on Section 4.1 (SHAPENETV2)

### ISSUE THREAD

**Issue by wdmwhh** [alextrevithick/GRF#5]
Hey, thanks for showing the great work.
I have a question on Figure 4, 

> "3) To further demonstrate the advantage of GRF over SRNs, we directly evaluate the trained SRNs model on unseen objects (of the same category) without retraining. For comparison, we also directly evaluate the trained GRF model on the same novel objects. Figure 4 shows the qualitative results. It can be seen that if not retrained, SRNs completely fails to".

According to that the SRNs model does not train on unseen objects, the latent code z for unseen object is not optimized, so is it randomly initialized? Then, how can it generates novel views of unseen cars similar to GT views? My understanding is that the randomly initialized latent code z may generate unpredictable cars, but similar to training set, which seems to be conflict with the above quoted words. It confuses me for hours.

**Comment by alextrevithick** [comment]
Thanks for your interest in this project!

Yes, you're correct. It's randomly initialized (or however the latent codes are initialized in the original SRNs). The experiment was mainly due to some reviewers' desires, as they wanted validation that SRNs needs to be optimized to find the latent codes. Of course, such a vector couldn't encode the appearance of any object without training, so it's basically just a representative-looking car that doesn't correspond to the desired car at all (hence the non-specific similarity between the rendered results).

**Comment by wdmwhh** [comment]
Thanks for your prompt reply. It solves my confusion.
