### ISSUE TITLE
Question about the CNN model

### ISSUE THREAD

**Issue by sstzal** [alextrevithick/GRF#8]
Hi, Alex
I notice that different CNN models are used for different datasets. I wonder if there were some special considerations when designing the CNNs. And if I want to design a CNN for my dataset, what should I pay attention to?
Thanks!

**Comment by alextrevithick** [comment]
Thanks for your question!

I don't think there is any set-in-stone rules about it. I would say for me I just wanted to have a "deep enough" unet that allowed for some global information to flow back to the final local features. I found that something like 4-5 layers works, with an optional global bottleneck in the middle (don't recommend this though). It also depends on the size of the images you are working with, because you don't need so many layers for the smaller images as the feature maps are already small. 

I guess it's just about finding a nice balance between time+memory and local+global features. 

Sorry that it's so unspecific, but hope it helps! Let me know about any other questions.

**Comment by sstzal** [comment]
Thanks！
